version: "2"
services:
  unity:
    build:
      context: .
        #dockerfile: ./Dockerfile
      args:
        GAME_CI_UNITY_EDITOR_IMAGE: ${GAME_CI_UNITY_EDITOR_IMAGE}
        PLATFORM: ${PLATFORM}
        UNITY_LICENSE: ${UNITY_LICENSE}
    image: ${IMAGE_TO_PUBLISH}
    environment:
      JOB: ${JOB}
      LANE: ${LANE}
